### ISSUE TITLE
Tempest CM1 doesn't apply

### ISSUE THREAD

**Issue by pajablons** [spacem/dngearsim#12]
Tempest CM1 gives a 50% pdmg buff.  Adding the skill doesn't immediately add the 50% pdmg, which I assume is probably intentional since it's not a passive, but a buff that activates (granted with potentially 100% uptime).  

As a workaround, I tried just adding 50% pdmg in the manual settings (going from 5->55%, because shard).  This actually caused a desync in stats between the game and calculator.  WITHOUT my CM1, in-game I'm at 699k while the calculator puts me at 698.  Fine, I assume that's just something I missed.  With CM1, the game puts me at 970k, while the calculator has me at only 926k... a very substantial difference.  Nothing else is changing other than the application of my CM1 (or the addition of flat 50% manual pdmg%) so I'm not really sure what would cause this.

It may be relevant that with small manual pdmg% numbers, the actual number is retained just fine, but when I put in 55% and save it, going back to edit shows that it's been changed to 55.00000000000001 (because floats are fun).  Probably irrelevant, but it's a thing.

**Comment by spacem** [comment]
I am in the process of migrating the gear sim to a different framework and I will look at the floating point number thing  and could possibly add the cm1 skill.

I need to implemented each skill separately and for classes I don't know I didn't want to guess what they do, I prefer them not to be there than to be wrong. Do you know is there any specific about this skill and its affect on the calculation?

Since it is a skill most likely you would need to add "skill pdmg%" since skill damage is calculated separately from normal pdmg% (the % on items). Apart from that I am not aware of any reason the numbers would be off sorry however. You could try checking agi/str/etc and might find the cause. There were updates recently to stats of gems, etc so you might need to re-add them to get the updated stats.

**Comment by pajablons** [comment]
Changing it to skill pdmg% does indeed fix it.  That's an interesting quirk of the game.  

For Tempest CM1, it's surprisingly simple: Using Kickshot or Somersault Dance gives you a 10 second buff for 50% (apparently Skill) pdmg.

![image](https://user-images.githubusercontent.com/15019601/37693666-a02f0136-2c97-11e8-8229-75761e86dbbf.png)

**Comment by spacem** [comment]
I think this skill has been working fine for a while now - let me know if there is still an issue
