### ISSUE TITLE
Silver Hunter's skill [Silver Hunter] doesn't increase Damage by INT

### ISSUE THREAD

**Issue by zeroztz** [spacem/dngearsim#8]
https://spacem.github.io/dngearsim/item?region=na&i=I1b9:_skills:E6:Jarcher:Vpve:.Silver-Hunter

"Damage increases by 20% of INT"

But it doesn't

**Comment by spacem** [comment]
Thanks for the ticket. Yes many skills are not implemented since I don't know their exact mechanics and don't have the classes to test. I can add it in later tonight so it works kindof like the crusader buf if you are happy to test it for me. Might be easier to talk on discord rather than here if you are on there.

**Comment by zeroztz** [comment]
Thanks for the support.

I would more than happy to test it. I have tuned my build that perfect(sometimes 1 INT off) match the result in dngearsim, without [Silver Hunter]. So the test should be straight-forward.

IGN: ZeroSilver
Discord: ZeroSilver#1845

**Comment by spacem** [comment]
I updated the sim for silver hunter - you might need to re-add the skill - let me know if it is not working as you expect
